target-version = "py38"

exclude = [
    "./src/tests", 
    "./src/integration_tests",
]

select = [
    # ruff's default set of rules: https://docs.astral.sh/ruff/configuration/#using-pyprojecttoml
    #"E4", "E7", "E9", "F",
    "E", "F",
    
    # pycodestyle: https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "W",
    
    # ruff: https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF",
    
    # pep8-naming: https://docs.astral.sh/ruff/rules/#pep8-naming-n
    # todo
    "N",
    
    # isort: https://docs.astral.sh/ruff/rules/#isort-i
    "I",

    # pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",

    # flake8-2020: https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
    "YTT",

    # flake8-bandit: https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    # todo
    #"S",

    # flake8-blind-except: https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    # todo
    #"BLE",

    # flake-8-bugbear: https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    # todo
    #"B"
]

ignore = [
    "RUF005", # "Consider {expression} instead of concatenation"
    "RUF012", # "Mutable class attributes should be annotated with `typing.ClassVar`"
    "E501", # "Line too long"
    "E731", # "Do not assign a `lambda` expression, use a `def`"
    "UP031" # "Use format specifiers instead of percent format"
]
