target-version = "py38"

exclude = [

]

select = [
    # ruff's default set of rules: https://docs.astral.sh/ruff/configuration/#using-pyprojecttoml
    #"E4", "E7", "E9", "F",

    # pyflakes: https://docs.astral.sh/ruff/rules/#pyflakes-f
    "F",

    # pycodestyle: https://docs.astral.sh/ruff/rules/#pycodestyle-e-w
    "E",
    "W",

    # mccabe: https://docs.astral.sh/ruff/rules/#mccabe-c90
    #"C90", # disabled, complexity is ok

    # isort: https://docs.astral.sh/ruff/rules/#isort-i
    "I",

    # pep8-naming: https://docs.astral.sh/ruff/rules/#pep8-naming-n
    "N",

    # pydocstyle: https://docs.astral.sh/ruff/rules/#pydocstyle-d
    #"D", # too pedantic, docs are not generated

    # pyupgrade: https://docs.astral.sh/ruff/rules/#pyupgrade-up
    "UP",

    # flake8-2020: https://docs.astral.sh/ruff/rules/#flake8-2020-ytt
    "YTT",

    # flake8-annotations: https://docs.astral.sh/ruff/rules/#flake8-annotations-ann
    #"ANN", # code is not be type annotated.

    # flake8-async: https://docs.astral.sh/ruff/rules/#flake8-async-async
    #"ASYNC", # code doesn't use Python's async

    # flake8-bandit: https://docs.astral.sh/ruff/rules/#flake8-bandit-s
    # todo
    #"S",

    # flake8-blind-except: https://docs.astral.sh/ruff/rules/#flake8-blind-except-ble
    # todo
    #"BLE",

    # flake8-boolean-trap: https://docs.astral.sh/ruff/rules/#flake8-boolean-trap-fbt
    #"FBT", # these aren't *that* confusing, c'mon.

    # flake-8-bugbear: https://docs.astral.sh/ruff/rules/#flake8-bugbear-b
    # todo
    #"B"

    # flake8-builtins: https://docs.astral.sh/ruff/rules/#flake8-builtins-a
    "A",

    # flake8-commas
    #"COM", # inserts trailing commas into function calls? too weird.

    # flake8-copyright
    #"CPY",

    # flake8-comprehensions
    "C4",

    # flake8-datetimez
    "DTZ",

    # flake8-debugger
    "T10",

    # flake8-django
    # "DJ" # not a django project

    # flake8-errmsg
    "EM",

    # flake8-executable
    "EXE",

    # flake8-future-annotations
    #"FA", # type annotations not used

    # flake8-implicit-str-concat
    "ISC",

    #flake8-import-conventions
    #"ICN", # highly specific to unused package imports

    # flake8-logging-format
    "G",

    # flake8-no-pep420
    #"INP", # todo, probably a good idea

    # flake8-pie
    "PIE",

    # flake8-print
    # "T20", # nothing wrong with print statements

    # flake8-pyi
    #"PYI", # typing not used

    # flake8-pytest-style
    #"PT", # todo

    #flake8-quotes
    #"Q", # todo, but too many changes required. bundle with PT perhaps

    # flake8-raise
    #"RSE", # "Removing the parentheses makes the code more concise" not a good reason imo.

    # flake8-return
    "RET",

    #"SLF", public/private separation not really followed in builder

    #"SLOT", todo

    # flake8-simplify
    "SIM",

    # flake8-tidy-imports
    "TID",

    # flake8-type-checking
    #"TCH", # typing not used

    # flake8-gettext
    "INT",

    # flake8-unused-arguments
    #"ARG", # todo: probably a good idea to review all of these

    # flake8-use-pathlib
    #"PTH", # pathlib not used

    # flake8-todos
    #"TD", # todo: probably a good idea

    # flake8-fixme
    # "FIX", # enabling this would prevent code with TODOs from passing CI. not practical.

    # eradicate
    #"ERA", # todo: review these

    # pandas-vet
    #"PD", pandas not used

    # pygrep-hooks
    "PGH",

    # pylint: https://docs.astral.sh/ruff/rules/#pylint-pl
    "PL",

    # tryceratops
    #"TRY", # todo

    "FLY",

    # NumPy-specific rules
    # "NPY" # numpy not used

    # "AIR", # airflow not used

    # Perflint
    "PERF",

    # refurb
    #"FURB", # still in preview

    # flake8-logging
    # "LOG", # still in preview

    # ruff: https://docs.astral.sh/ruff/rules/#ruff-specific-rules-ruf
    "RUF",
]

ignore = [
    "RUF005", # "Consider {expression} instead of concatenation". solution is unreadable and optimised for speed.
    "RUF012", # "Mutable class attributes should be annotated with `typing.ClassVar`". # code is not type annotated
    "E501", # "Line too long". long lines are ok, contortions to obey rule are not ok.
    "E731", # "Do not assign a `lambda` expression, use a `def`". lambdas are fine.
    "UP031", # "Use format specifiers instead of percent format". percent formatters are fine. f-strings absorb the environment.
    "PLR0913", # "Too many arguments in function definition". complexity is ok.
    "PLR0915", # "Too many statements". complexity is ok.
    "PLR0912", # "Too many branches". complexity is ok
    "PIE804", # "Unnecessary dict kwargs", boto often requires many long parameter names. dicts are nicer in this case.
    "RET504", # "Unnecessary assignment to {name} before return statement". typically deliberate for readability/debugging/extensibilty.
    "TRY300", # "Consider moving this statement to an else block", might have merit but syntax is strange and unfamiliar
]
