#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ ! -d venv ]; then
    source update.sh
fi

source ./venv/bin/activate

# ad-hoc permissions if they exist
if [ -f .aws-credentials.env ]; then
    source ./.aws-credentials.env
fi

# a wrapper around fabric that activates the elife-builder virtualenv

fabric=$(which fab)
if [ -e newrelic.ini ]; then
    NEW_RELIC_CONFIG_FILE=./newrelic.ini newrelic-admin run-program $fabric "$*" -f src/fabfile.py
else
    $fabric "$*" -f src/fabfile.py
fi
