#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd $DIR

if [ ! -d venv ]; then
    ./update.sh
fi

source ./venv/bin/activate

# TODO: remove
# ad-hoc permissions if they exist
if [ -f .aws-credentials.env ]; then
    source ./.aws-credentials.env
fi

if [ -f .use-threadbare.flag ]; then
    export BLDR_BACKEND=threadbare
fi

python src/taskrunner.py "$*"
