version: "3.8"
services:
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    image: builder:${TAG-local}
    container_name: ubuntu-builder
    stdin_open: true
    tty: true 
    environment: 
      - TZ='Europe/London'
    volumes:
      - '/etc/timezone:/etc/timezone:ro'
      - '/etc/localtime:/etc/localtime:ro'
      - ${CUSTOM_SSH_KEY-~/.ssh/id_rsa}:/root/.ssh/id_rsa:ro
      - ${CUSTOM_SSH_KEY-~/.ssh/id_rsa}.pub:/root/.ssh/id_rsa.pub:ro
      - ${CUSTOM_AWS_CREDENTIALS-~/.aws/credentials}:/root/.aws/credentials:ro
      - ./:/builder:rw