from ubuntu:20.04

WORKDIR /builder
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata build-essential software-properties-common git python3 python3-venv python3-dev vagrant awscli wget --no-install-recommends
RUN wget https://releases.hashicorp.com/vault/0.11.6/vault_0.11.6_linux_amd64.zip -O vault.zip && unzip ./vault.zip -d /bin && rm ./vault.zip
RUN echo 'eval $(ssh-agent); ssh-add;' >> ~/.bashrc

SHELL ["/bin/bash", "-c"]
