FROM python:2.7.15-slim-stretch

RUN pip install virtualenv wheel "pip==20.3.4" --upgrade
RUN mkdir /venv && virtualenv --python=python2 /venv
COPY py2-requirements.txt /requirements.txt
RUN /venv/bin/pip install -r /requirements.txt
CMD /venv/bin/python
