#!/usr/bin/env python
from gevent import monkey
monkey.patch_all()

import pytest
import re
import sys
if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
    sys.exit(pytest.main())

