#!/bin/bash
set -e

if [ -e .use-python-3.flag ]; then
    image=py3
else
    image=py2
fi

docker build \
    -f "Dockerfile.${image}" \
    -t "elifesciences/builder:${image}" \
    . \
    1>&2

docker run \
  -v $(pwd):/srv/builder \
  -w /srv/builder \
  "elifesciences/builder:${image}" \
  /venv/bin/python $* 
